apiVersion: apps/v1
kind: Deployment
metadata:
  name: apiserver
  labels:
    app: apiserver
spec:
  replicas: 2
  selector:
    matchLabels:
      app: apiserver
  template:
    metadata:
      name: apiserver-pod
      labels:
        app: apiserver
    spec:
      containers:
        - name: apiserver
          image: shahincsejnu/httpapiserver:v1.0.5
          imagePullPolicy: IfNotPresent
          ports:
            - name: api-port
              containerPort: 8080
